# Generated by Django 2.2.16 on 2022-06-07 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220607_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='title',
            new_name='name',
        ),
    ]
